# Generated by Django 5.0.4 on 2024-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
